name: Test
on: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [2.7, 3.9]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install pipenv
        run: pip install pipenv==2018.11.26

      - name: Install dependencies
        run: pipenv install --skip-lock -d

      - name: Install dependencies for Python 2.7
        run: pipenv install --skip-lock configparser==3.5.0 futures==3.2.0 urllib3==1.22
        if: matrix.python-version == '2.7'

      - name: Check isort
        run: pipenv run isort . --check-only --diff --quiet

      - name: Check flake8
        run: pipenv run lint
  unittest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install pipenv
        run: pip install pipenv==2018.11.26

      - name: Install dependencies
        run: pipenv install --skip-lock -d

      - name: Run UnitTest
        run: pipenv run unittest
